# **Heart Failure Project**

## **Step 1 - Predict the readmisson 6 months after discharge**

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

np.random.seed(12345)

path1 = 'dat.csv'
data = pd.read_csv(path1)

data.describe()

,Unnamed: 0,inpatient.number,visit.times,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,weight,...,carboxyhemoglobin,body.temperature.blood.gas,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,anion.gap,free.calcium,total.hemoglobin,GCS,dischargeDay
count,2008.00000,2008.000000,2008.000000,2008.000000,2008.000000,2008.000000,2008.000000,2008.000000,2008.000000,2008.000000,...,992.000000,993.0,993.000000,993.000000,992.000000,993.000000,993.000000,992.000000,2008.000000,2008.000000
mean,1004.50000,797747.542829,1.092629,36.416484,85.235060,19.085657,131.056773,76.573207,94.734396,52.483715,...,0.605645,37.0,95.806647,108.121853,94.938710,14.022457,1.110393,124.088710,14.831175,9.420817
std,579.80399,41127.801740,0.365946,0.439529,21.539214,1.737546,24.741670,14.461247,16.323762,10.895935,...,0.560946,0.0,6.212864,37.422666,6.205458,4.153747,0.052645,24.638623,1.179836,8.030256
min,1.00000,722128.000000,1.000000,35.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,37.0,25.000000,20.000000,24.300000,-1.200000,0.890000,35.000000,3.000000,1.000000
25%,502.75000,763164.500000,1.000000,36.200000,70.000000,18.000000,113.000000,65.000000,83.333333,45.000000,...,0.300000,37.0,95.000000,80.000000,94.500000,11.700000,1.080000,110.000000,15.000000,6.000000
50%,1004.50000,798758.000000,1.000000,36.300000,82.000000,19.000000,130.000000,76.000000,93.333333,50.000000,...,0.400000,37.0,98.000000,102.000000,96.600000,13.800000,1.110000,127.000000,15.000000,8.000000
75%,1506.25000,829399.750000,1.000000,36.500000,98.000000,19.000000,146.250000,85.000000,104.666667,60.000000,...,0.800000,37.0,99.000000,134.000000,97.800000,16.100000,1.140000,139.000000,15.000000,10.000000
max,2008.00000,905720.000000,5.000000,42.000000,198.000000,36.000000,252.000000,146.000000,181.333333,115.000000,...,5.300000,37.0,100.000000,255.000000,99.100000,43.700000,1.390000,203.000000,15.000000,123.000000

## Pre-processing of data

In [ ]:

# Definition of target: readmission of a patient within 6 months
X = data.drop(columns=['re.admission.within.6.months'])  
y = data['re.admission.within.6.months'].values

#Splitting the data into to test and train data (80% train - 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)